-- Create a function to trigger embedding generation via edge function
CREATE OR REPLACE FUNCTION public.trigger_embedding_generation()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  edge_function_url TEXT;
  service_role_key TEXT;
BEGIN
  -- Get Supabase URL from environment (we'll call the edge function via pg_net)
  -- For now, we'll set embedding to NULL to mark it needs regeneration
  -- The edge function can be called manually or via a scheduled job
  
  -- Mark the embedding as needing regeneration
  NEW.embedding := NULL;
  NEW.updated_at := now();
  
  RETURN NEW;
END;
$$;

-- Create trigger for INSERT and UPDATE on knowledge_base
DROP TRIGGER IF EXISTS knowledge_base_embedding_trigger ON public.knowledge_base;

CREATE TRIGGER knowledge_base_embedding_trigger
BEFORE INSERT OR UPDATE OF title, content ON public.knowledge_base
FOR EACH ROW
EXECUTE FUNCTION public.trigger_embedding_generation();

-- Add a comment explaining the trigger
COMMENT ON FUNCTION public.trigger_embedding_generation() IS 'Clears embedding on content change so it can be regenerated by the generate-embeddings edge function';