// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';


const SUPABASE_URL = "https://qlrnewbkolxjdtfffuml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFscm5ld2Jrb2x4amR0ZmZmdW1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUzNjAzMDMsImV4cCI6MjA4MDkzNjMwM30.3oTFUgh8RdxzRu69FHPd5bjzYSwbQhGesdi6ynopQMk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
